development: &defaults
  bucket: <%= ENV['S3_BUCKET'] %>
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
test:
  bucket: cards-test
  access_key_id: xxx
  secret_access_key: xxx
production:
  <<: *defaults