- 
  name: Lucie Rico
  slug: lucie
  role: Réalisatrice
  bio: |
    Originaire de Perpignan, elle fait ses études en cinéma, lettres et communication à Paris. Ses premiers films, documentaires, se déroulent entre Buenos Aires et Taiwan et ont été diffusés dans plusieurs festivals à travers le monde. Elle prépare actuellement un long fictionnel et une série transmédia.   

      En parallèle, elle est responsable éditoriale du réseau social d'auteurs WeLoveWords et participe au jury de nombreux prix littéraires.
  facebook:
    name: lucie.rico
    url: "http://facebook.com/lucie.rico"
  twitter:
    name: "@Lucie_R"
    url: "http://twitter.com/Lucie_R"
-
  name: Garance Moreau
  slug: garance
  role: Actrice
  bio: |
    sdsdsdsd
-
  name: Andreas B. Krueger
  slug: andreas
  role: Chef opérateur
  bio: |
    Chef-opérateur et photographe, Andreas a fait ses armes aux Beaux-Arts de Berlin avant de terminer ses études à Paris. Se partageant entre les deux villes, il poursuit aussi bien des commandes (pub/journalisme) ainsi que ses projets personnels qui sont exposés régulièrement (Arles, Paris, Lyon, Berlin). Le sujet intrigant du projet et l'aspect de la relecture ont suscité son intérêt – son expérience dans le domaine du court-métrage et son regard sang-froid ont fait la combinaison idéale afin de collaborer avec Lucie Rico sur The Big Shake.
  facebook:
    name: andreas.b.krueger.photography
    url: https://www.facebook.com/andreas.b.krueger.photography
  twitter: 
    name: '@abkPhoto'
    url: http://twitter.com/abkPhoto
  website:
    name: andreasbkrueger.com
    url: http://www.andreasbkrueger.com
-
  name: Emmanuel Turlay
  slug: manu
  role: Développeur
  bio: |
    Ancien physicien des particules au CERN, Emmanuel bifurque vers le web en rejoignant Official.fm en 2010 et lance releas.io en 2012 avant d'intégrer WeLoveWords en 2013. Spécialiste de la supersymmétrie, des produits web et des applications Ruby on Rails, il aime écrire du code lisible mais concis, cannonique mais audacieux, pour des projets auxquels il croit.
  website:
    name: turlay.net
    url: http://turlay.net
  facebook:
    name: neutralino1
    url: http://facebook.com/neutralino1
  twitter:
    name: '@neutralino1'
    url: http://twitter.com/neutralino1